# Generated by Django 6.0.5 on 2026-05-13 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='working_hours',
            field=models.CharField(default='', max_length=100),
        ),
    ]
